module.exports = {
  TWITCH_BOT_USERNAME: process.env.TWITCH_BOT_USERNAME,
  TWITCH_OAUTH_TOKEN: process.env.TWITCH_OAUTH_TOKEN,
  TWITCH_CHANNEL: process.env.TWITCH_CHANNEL,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  GOOGLE_CALENDAR_ID: process.env.GOOGLE_CALENDAR_ID
};
